# Generated by Django 3.2.3 on 2021-06-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.IntegerField()),
                ('descripcion', models.CharField(default='DESCRIPCION DEL PRODUCTO', max_length=100)),
                ('marca', models.CharField(default='MARCA', max_length=100)),
                ('modelo', models.CharField(default='MODELO', max_length=100)),
                ('pr_csto', models.IntegerField()),
                ('pr_vta', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('cod_barra', models.IntegerField()),
                ('stock_vta', models.IntegerField()),
                ('stock_dev', models.IntegerField()),
                ('fec_adq', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudrest.bodega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudrest.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.IntegerField()),
                ('descripcion', models.CharField(default='DESCRIPCION DEL PRODUCTO', max_length=100)),
                ('marca', models.CharField(default='MARCA', max_length=100)),
                ('modelo', models.CharField(default='MODELO', max_length=100)),
                ('pr_csto_clp', models.IntegerField()),
                ('pr_csto_intr', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('cod_barra', models.IntegerField()),
                ('stock_vta', models.IntegerField()),
                ('stock_dev', models.IntegerField()),
                ('n_lote', models.IntegerField()),
                ('an_lote', models.IntegerField()),
                ('al_lote', models.IntegerField()),
                ('pr_lote', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='prod_prov')),
                ('fec_adq', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudrest.bodega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudrest.categoria')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudrest.moneda')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
