# Generated by Django 3.2.3 on 2021-07-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudrest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prod_prov',
            old_name='precio',
            new_name='pr_vta',
        ),
    ]
